### ISSUE TITLE
Pull To Refresh

### ISSUE THREAD

**Issue by nie55352177** [cipchk/ngx-weui#10]
我正在使用Pull To Refresh组件实现一个下拉加载更多的功能，这个组件有没有设置disabled的方法。我想在没有更多数据时禁用它。类似微信聊天下拉加载数据。

**Comment by cipchk** [comment]
当前没有能禁止的办法，在下一版本中会加上该功能。

**Comment by cipchk** [comment]
release 1.0.7, see [CHANGELOG](https://github.com/cipchk/ngx-weui/blob/master/CHANGELOG.md).

If it solves the problem, please close this issue
