### ISSUE TITLE
Expression has changed after it was checked. Previous value: 'active: false'. Current value: 'active: false'.

### ISSUE THREAD

**Issue by jasminecjc** [cipchk/ngx-weui#100]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
从不同页面进入，选中的都是第一个tab

## Expected behavior
从不同页面进入，选中当前menu

## Environment

```
<weui-navbar class="menu">
  <weui-tab *ngFor="let menu of menuService.userMenu" heading="{{menu.name}}" active="{{path===menu.name}}" (select)="routerChange($event)">
  </weui-tab>
</weui-navbar>
```
Angular version: X.Y.Z

ngx-weui version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

Others:

</code></pre>

**Comment by cipchk** [comment]
请尽可能通过 https://stackblitz.com/edit/ngx-weui 重现问题
