### ISSUE TITLE
cityPicker自定义数据ngModel无法正确绑定

### ISSUE THREAD

**Issue by tjzfg** [cipchk/ngx-weui#101]
既然cityPicker提供dataMap，允许使用自定义数据，是不是不要在writeValue方法中限定value长度为6比较合适？

**Comment by tjzfg** [comment]
另外还有一个问题，如果数据没有下级地区，sub必须不提供，如果提供空数组属性值会导致组件无法正常加载

**Comment by cipchk** [comment]
citypicker 采用的是国家标准地址区域代码信息规则，`dataMap` 只是对于数据键值名的转换而已。
