### ISSUE TITLE
卡色啊卡色，又来吐槽了……

### ISSUE THREAD

**Issue by woodstream** [cipchk/ngx-weui#105]
被你的文档偷袭了……首先强调这话没有恶意！文档没有说以缩写别名方式导入使用啊，直到看到源码

> export { ToptipsModule as ɵcb } from './src/toptips/toptips.module';
> export { ToptipsService as ɵcd } from './src/toptips/toptips.service';
> export { FileThumbDirective as ɵo } from './src/uploader/file-thumb.directive';
> export { UploaderConfig as ɵp } from './src/uploader/uploader.config';

**Comment by cipchk** [comment]
不要在意这个，也不应该去调用这些“别名”的东西，这是 rollup 产生的。

**Comment by woodstream** [comment]
因为无法import模块

**Comment by cipchk** [comment]
能否具体的表述？最好通过 https://stackblitz.com 重现。

> 不要让别人猜，干，怎么每个人都这毛病。

**Comment by woodstream** [comment]
回一句话只是手机党打字不客易。环境angular6，装完ngx-weui后正常使用，但以service方式调用反馈组件时，无法import，如import ToptipsService提示没有找到该模块，以“别名”方式import可正常使用，打开D文件就是截图内容

**Comment by cipchk** [comment]
https://stackblitz.com/edit/ngx-weui

> 国内的开源真不把作者的时间当时间，干。
