### ISSUE TITLE
weui-gallery

### ISSUE THREAD

**Issue by RiRiGit** [cipchk/ngx-weui#108]
weui-gallery不能缩放图片, 想问问大佬们有做过图片缩放功能的吗?

**Comment by cipchk** [comment]
你可以使用第三方组件，或者直接调用 weui api。当然我建议使用后者。

**Comment by cipchk** [comment]
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421141115

**Comment by RiRiGit** [comment]
原来大佬指的是jssdk, 感谢指点, 谢谢啦~~
