### ISSUE TITLE
Pull To Refresh组件问题

### ISSUE THREAD

**Issue by nie55352177** [cipchk/ngx-weui#11]
该组件不会判断滚动条位置，只要下拉就会触发。导致在移动端和滚动条下拉产生冲突。
该组件配合上拉加载更多使用时，无法下拉查看前面的数据。

**Comment by nie55352177** [comment]
请问作者是否考虑解决此问题？

**Comment by cipchk** [comment]
我没有明白你什么意思！

**Comment by nie55352177** [comment]
我觉得ptr触发机制应该先判断容器滚动条是否在顶部。

**Comment by cipchk** [comment]
PTR 的触发是在容器滚动条下拉时触发，所以无须判断是否为顶部

**Comment by nie55352177** [comment]
那如果滚动条位置在容器中间就无法查看容器上面的内容，因为下拉是触发ptr回调而不是滚动条上滑。

**Comment by cipchk** [comment]
@nie55352177 对于局部下拉刷新的确如此，从 `weui-ptr` 角度来讲也是难于解决这个问题的。

**Comment by cipchk** [comment]
我先关闭，如再有疑问，可以重新打开。

**Comment by Zhouuuuuuuuu** [comment]
@nie55352177 我也遇到了这个尴尬的问题，请问你是怎么解决的？
