### ISSUE TITLE
weui-vcode 作为输出输出属性

### ISSUE THREAD

**Issue by jonashao** [cipchk/ngx-weui#110]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

weui-vcode 是作为<input>标签的输入属性
```
 <button class="weui-vcode-btn"
                  [weui-vcode]="onSendCode"
                  weui-seconds="120"
                  weui-tpl="${num}s"
                  weui-error="重新发送">获取验证码
          </button>
```
在onSendCode的定义里面，如果需要使用类的成员变量，会因为`this`指错的问题而无法使用。
如：
```
  onSendCode (): Observable<boolean> {
    console.log(this.userService);
    return userService.obtainLoginCaptcha(this.res.phone)
      .map((token: TokenResponse) => {
        this.res.token = token.token;
        return (token && token.token != null);
      });
  }
```
这里的`this`实际上指向的是`VCodeDirective `,由于VCodeDirective 内部没有`userService`这个成员变量，如上使用会导致空指针异常。

## Expected behavior

发送验证码应该类似于点击按钮事件，作为输出属性
## Environment

<pre><code>
Angular version:  5.2.0

ngx-weui version: 5.0.4

Browser:
- [x] Chrome (desktop) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] IE version XX

Others:

</code></pre>

**Comment by cipchk** [comment]
```ts
onSendCode = (): Observable<boolean> => {}
```

**Comment by myFirstway** [comment]
遇到同样问题，还望解答一下应该怎么用这个组件

**Comment by myFirstway** [comment]
> ```ts
> onSendCode = (): Observable<boolean> => {}
> ```
代码如下:
`  onSendCode(): Observable<boolean> {
    console.log('click onsendCode');
   return this.smsService.sendsms({phone: this.res.phone, wId: this.ut, deviceNo: this.setting.deviceno}).pipe(map((res: any) => {
      if (res.data === 200) {
         return true;
      } else {
        return false;
      }
    }));
  }`
错误如下:
`VM5140:1 ERROR TypeError: Cannot read property 'sendsms' of undefined
    at t.onSendCode [as onSend] (main.6457f74237301abee4ce.js:1)
    at t._onClick (main.6457f74237301abee4ce.js:1)
    at Object.handleEvent (main.6457f74237301abee4ce.js:1)
    at Object.handleEvent (main.6457f74237301abee4ce.js:1)
    at Object.handleEvent (main.6457f74237301abee4ce.js:1)
    at eu (main.6457f74237301abee4ce.js:1)
    at main.6457f74237301abee4ce.js:1
    at HTMLButtonElement.<anonymous> (main.6457f74237301abee4ce.js:1)
    at e.invokeTask (polyfills.bebee6a5ef0ece001bc6.js:1)
    at Object.onInvokeTask (main.6457f74237301abee4ce.js:1)`

**Comment by cipchk** [comment]
@myFirstway 

```ts
onSendCode: () => Observable<boolean> {
    console.log('click onsendCode');
   return this.smsService.sendsms({phone: this.res.phone, wId: this.ut, deviceNo: this.setting.deviceno}).pipe(map((res: any) => {
      if (res.data === 200) {
         return true;
      } else {
        return false;
      }
    }));
  }
```
