### ISSUE TITLE
weui-cells weui-cells_radio weui-cells_checkbox 在其他css class下显示不正常

### ISSUE THREAD

**Issue by Shakell** [cipchk/ngx-weui#112]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ x ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>
具体情况可查看：
https://stackblitz.com/edit/ngx-weui-u9cpma?file=app/app.component.ts

**Comment by cipchk** [comment]
`.weui-article` 会对所有子 `p` 增加一个外边距，布局应该是 `div` 而不是使用段落 `p`。
