### ISSUE TITLE
Swiper在angular6上构建报错

### ISSUE THREAD

**Issue by weber0000** [cipchk/ngx-weui#114]
报错如下：
 ERROR in Error during template compile of 'AppModule'   Function calls are not supported in decorators but 'SwiperModule' was called.

ng build --base-href /kiloeye/ --prod  --configuration=test

**Comment by weber0000** [comment]
请问这是什么原因呢？

**Comment by lc-01010** [comment]
运行 npm run build报错如下：
ERROR in : Unexpected value 'SwiperModule in C:/Users/T01/Documents/workbook/taozhib/node_modules/ngx-weui/weui.d.ts' imported by the module 'RoutesModule in C:/Users/T01/Documents/workbook/taozhib/src/app/routes/routes.module.ts'. Please add a @NgModule annotation.
