### ISSUE TITLE
引入的 _preserve-white-spaces.less 样式，会导致 全页宽度的 button 错位

### ISSUE THREAD

**Issue by dusdong** [cipchk/ngx-weui#115]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[x] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

官方的 example 就是错位的：
[https://cipchk.github.io/ngx-weui/#/components/button](https://cipchk.github.io/ngx-weui/#/components/button)

![tim 20180702202623](https://user-images.githubusercontent.com/3461709/42163737-3a422a92-7e36-11e8-9f3c-b8376ef636c0.png)

## Environment

<pre><code>
Angular version: X.Y.Z

ngx-weui version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

Others:

</code></pre>

**Comment by sfwxp945** [comment]
问个题外的问题，我刚刚接触这个UI，想问下，要覆盖ui样式，看说明写的是在styles.less里面重新声明变量就好，可是我覆盖了变量还是没有任何作用。不知道要怎么做？
