### ISSUE TITLE
Navbar需求

### ISSUE THREAD

**Issue by hemiaoio** [cipchk/ngx-weui#118]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Expected behavior

目前的Navbar功能太过单调了，感觉有点对不起这个名称，有木有计划实现类似微信Header的那样的Navbar? 或者类似[ionic navigation](https://ionicframework.com/docs/components/#navigation)的实现？

## Environment

<pre><code>
Angular version: X.Y.Z

ngx-weui version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

Others:

</code></pre>

**Comment by cipchk** [comment]
没有计划，目前的状态是只会依据weui来，不会考虑额外的。
