### ISSUE TITLE
运行npm install后，在运行npm serve遇见缺少引用文件的错误

### ISSUE THREAD

**Issue by AlanFHuang** [cipchk/ngx-weui#119]
ERROR in src/app/core/menu.service.ts(2,22): error TS2307: Cannot find module '.
./routes/docs/meta'.
src/app/routes/components/article/article.component.ts(4,22): error TS2307: Cann
ot find module '../meta'.
src/app/routes/components/article/article.component.ts(5,25): error TS2307: Cann
ot find module '../examples'.
src/app/routes/docs/article/article.component.ts(3,22): error TS2307: Cannot fin
d module '../meta'.

**Comment by a641334373** [comment]
me too
