### ISSUE TITLE
Cannot find module 'ngx-weui/chart-g2'

### ISSUE THREAD

**Issue by Hzert** [cipchk/ngx-weui#123]
是需要安装么？

**Comment by cipchk** [comment]
参考：https://cipchk.github.io/ngx-weui/#/components/chart%20g2-mobile

**Comment by Hzert** [comment]
报错是解决了。import { ChartG2Directive } from 'ngx-weui/chart-g2'   显示找不到模块。所以我在app.module里引用了import { ChartG2Module } from 'ngx-weui';
在需要用到图表的component里面只能import { ChartG2Directive } from 'ngx-weui'，没有报错。但是页面显示不出来图表。还请解答一下～谢谢

**Comment by cipchk** [comment]
https://cipchk.github.io/ngx-weui/#/components/chart%20g2-mobile
