### ISSUE TITLE
企业微信应用中，PickerService不能打开datePicker

### ISSUE THREAD

**Issue by RookieLittleFatty** [cipchk/ngx-weui#126]
![image](https://user-images.githubusercontent.com/32049377/44977516-cf260580-af9a-11e8-96fa-fdcb9711f396.png)

项目中需要通过picker3修改每条记录的时间，是通过PickerService触发的，下面是我的代码

![image](https://user-images.githubusercontent.com/32049377/44977434-9423d200-af9a-11e8-8a63-05a24cd7bea2.png)

在pc端用chrome模拟器看的时候是正常的，但是在手机端测试的时候，进入了click的这个方法，但是通过pickerservice没有打开选择弹框。于是我写了picker1和picker2做测试，发现picker1可以弹出选择，但是超出屏幕宽度，picker2还是通过pickerService触发的，只传入了一个Type是date，手机端点击无反应。
下面是picker2的方法
` showDate() {
    this.ps.showDateTime('date').subscribe((res: any) => {
      alert('success');
    });
  }`

**Comment by cipchk** [comment]
麻烦提供一个可重现在线示例。

**Comment by RookieLittleFatty** [comment]
这个在pc看是正常的，在手机企业微信应用中看是不正常的，所以我也不太清楚这个我应该怎么提供给你呢？

**Comment by cipchk** [comment]
我需要一个可重现在线示例，哪怕在PC上是正常的，但能确保企业微信下有问题的。否则我无法定位问题根源。

**Comment by RookieLittleFatty** [comment]
我可以提供外网地址，但是可能在调试器里无法查看资源，这样也可以吗？

**Comment by cipchk** [comment]
建议在 [Stackblitz](https://github.com/cipchk/ngx-weui#usage--demo) 提供一个完整的示例。

**Comment by cipchk** [comment]
建议从自身找问题：

![wechat image_20180903182642](https://user-images.githubusercontent.com/2987467/44982003-ea970d80-afa6-11e8-975f-17ea04026d6d.png)

**Comment by RookieLittleFatty** [comment]
感谢你的回复，我想问下你的测试机是iPhone还是安卓？并且还有点不一样是，我在click事件中调用了stopPropagation方法，其他我能想到的影响的地方，好像没有了， 我会再看看的

**Comment by RookieLittleFatty** [comment]
谢谢你的回复和帮助，已经找到原因。
