### ISSUE TITLE
Pull To Refresh 组件在手机端和滚动事件冲突的问题,有解决方案吗?

### ISSUE THREAD

**Issue by cirelir** [cipchk/ngx-weui#128]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
手机端浏览器查看存在pullToRefresh组件与滚动事件冲突的问题,

## Expected behavior
手机端的浏览器滚动时不会触发pullToRefresh组件的事件

## Environment
Angular version: 6.2.4
ngx-weui version: 5.0.4

**Comment by cipchk** [comment]
不支持。
