### ISSUE TITLE
是否考虑加入prompt组件

### ISSUE THREAD

**Issue by nie55352177** [cipchk/ngx-weui#13]
rt

**Comment by cipchk** [comment]
[dialog](https://cipchk.github.io/ngx-weui/#/docs/components/dialog) 就是。

**Comment by nie55352177** [comment]
我看dialog的弹出内容只能是文字，是否考虑增加支持HTML？比如input文本框

**Comment by cipchk** [comment]
已经在做了，下一版本会更新。

**Comment by cipchk** [comment]
我先关闭，如再有疑问，可以重新打开。
