### ISSUE TITLE
Uploader 如何跟阿里OSS集成呢 不能设置form-data 

### ISSUE THREAD

**Issue by semprone** [cipchk/ngx-weui#130]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

ngx-weui version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

Others:

</code></pre>

**Comment by cipchk** [comment]
使用 `params` 参数。
