### ISSUE TITLE
InfiniteLoader与hammerjs冲突，导致页面在ios上无法滚动

### ISSUE THREAD

**Issue by tjzfg** [cipchk/ngx-weui#134]
感谢提供这么好的组件库
```
<weui-infiniteloader #loader>
  <div class="df-panel order-panel" (press)="toSel()">

```
代码会导致ios页面滚动失效，android好像正常，有办法一起使用吗？

**Comment by cipchk** [comment]
@tjzfg 麻烦提供一下重现示例。

**Comment by tjzfg** [comment]
需要mobile端才可以重现，已经找到问题和解决方案，是hammerjs的bug
参看https://stackoverflow.com/questions/51815182/hammerjs-in-safari-scroll-issue，感谢！
