### ISSUE TITLE
dialog 组件不支持自定义html

### ISSUE THREAD

**Issue by lynings** [cipchk/ngx-weui#14]
![image](https://user-images.githubusercontent.com/14272789/28066287-f42f4d9e-666e-11e7-9a98-3587cd4baa05.png)
![image](https://user-images.githubusercontent.com/14272789/28066503-cecbccd4-666f-11e7-833d-f1e5f399c4a0.png)

**Comment by cipchk** [comment]
原本是中午要发布新版本的，结果网络问题，无法发布至Npm中，现已经更新至 1.0.8。
