### ISSUE TITLE
请教，8.0.0版本中ng build -prod报错

### ISSUE THREAD

**Issue by NuanYangDaDa** [cipchk/ngx-weui#152]
请教，我采用angulr8+ngx-weui 8.0.0开发，当使用ng build -prod时报错，
`ERROR in ngx-weui/gallery/ngx-weui-gallery.d.ts.GalleryComponent.html(7,7): Expected 0 arguments, but got 1.
ngx-weui/gallery/ngx-weui-gallery.d.ts.GalleryComponent.html(8,7): Expected 0 arguments, but got 1.
ngx-weui/picker/ngx-weui-picker.d.ts.PickerComponent.html(7,3): Expected 0 arguments, but got 1.
ngx-weui/ptr/ngx-weui-ptr.d.ts.PTRComponent.html(11,7): Property 'loading' is private and only accessible within class 'PTRComponent'.
(1,1): Directive AccordionComponent, Property 'closeOthers' does not exist on type 'AccordionComponent'. Did you mean '_closeOthers'?`

使用 ng server或ng build都没报错，我是angular初学者，请教一下这个怎么解决

**Comment by cipchk** [comment]
这是一个BUG，我会修复它
