### ISSUE TITLE
Uploader中的index无效

### ISSUE THREAD

**Issue by pengcl** [cipchk/ngx-weui#154]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

ngx-weui version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

Others:

</code></pre>

**Comment by cipchk** [comment]
不明白你的意思。

**Comment by pengcl** [comment]
文件对象 FileItem 中的 index 索引 永远是0
