### ISSUE TITLE
您好，我在使用datePicker和cityPicker的时候选择省之后后面的市不会跟着变化，并且样式也错乱了，麻烦看下

### ISSUE THREAD

**Issue by ccjhpu** [cipchk/ngx-weui#156]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

ngx-weui version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

Others:

</code></pre>

**Comment by ccjhpu** [comment]
这个是报错信息 
ERROR TypeError: Cannot read property 'target' of undefined
    at PickerComponent.push.../../node_modules/ngx-weui/__ivy_ngcc__/fesm5/ngx-weui-picker.js.PickerComponent._onFocus (ngx-weui-picker.js:702)
    at PickerComponent_input_0_Template_input_focus_0_listener (ngx-weui-picker.js:40)
    at executeListenerWithErrorHandling (core.js:16332)

**Comment by cipchk** [comment]
如果你在使用lvy，那抱歉目前还不支持，会在ng9正式版开始我在做这方面的工作。

**Comment by ccjhpu** [comment]
您好我是angular初级用户，在麻烦您讲下 lvy是哪个知识点，是因为我项目使用ng9的原因吗？

**Comment by ccjhpu** [comment]
请问适配到angular9大概还需要多长时间？

**Comment by cipchk** [comment]
是的，ng9默认开启lvy。

**Comment by ccjhpu** [comment]
可以关闭lvy或者其他折中的解决方案吗，麻烦了

**Comment by ccjhpu** [comment]
可以关闭lvy或者其他折中的解决方案吗，麻烦了，因为团队项目之前是使用 NgZorroAntdMobile组件库，在升级到ng9之后同样遇到build报错到问题，没想到在尝试使用ngx-weui时也遇到问题了，麻烦了

**Comment by cipchk** [comment]
可以关闭lvy，可以自行google。

**Comment by ccjhpu** [comment]
您好，我在看文档的时候找到了一个替代的解决方案，现在有个问题就是我该如何设置这个日期的最大值和最小值`<div class="weui-cell">
        <div class="weui-cell__hd"><label for="" class="weui-label">日期</label></div>
        <div class="weui-cell__bd">
          <input class="weui-input" [(ngModel)]="res.date" name="date" type="date" value="" />
        </div>
      </div>`

**Comment by cipchk** [comment]
原生的话，你可以参考 https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#max

**Comment by ccjhpu** [comment]
刚试了，在iOS系统里没有效果

**Comment by Grenwei** [comment]
> 可以关闭lvy，可以自行google。

你好，我目前的版本是Angular8，但是也遇到了Cannot read property 'target' of undefined这个问题。
