### ISSUE TITLE
swipe单元滑块打包有问题

### ISSUE THREAD

**Issue by nie55352177** [cipchk/ngx-weui#17]
`ng build --prod` 打包时报错
![qq 20170719095847](https://user-images.githubusercontent.com/16702082/28347580-81fc2632-6c6a-11e7-9012-ecb4ab7d400a.jpg)

看这意思应该是说`SwipeDirective`重复`declarations`了。
但是我不`declarations`它的话又没有效果。
十万火急！

**Comment by cipchk** [comment]
能否提供 `src/app/directive.ts` 的内容，`ngx-weui` 并没有两个 `SwipeDirective`，可能是因为你的 `src/app/directive.ts` 里头定义了些什么吧。

**Comment by nie55352177** [comment]
![qq 20170719105645](https://user-images.githubusercontent.com/16702082/28348730-1140f394-6c71-11e7-8c1f-24e3766ab3c0.jpg)

**Comment by cipchk** [comment]
`AppDirective.PhotoSwipeDirective.SwipeDirective` 如果允许的情况下换个名称，因为这里的确是导入了两个相同名称的指令。

**Comment by cipchk** [comment]
就我目前了解，好像没有别的办法了。

**Comment by cipchk** [comment]
@nie55352177 为什么你不直接在所属的模块导入 `import { CellModule } from 'ngx-weui/cell';` 就可以直接使用 `weui-swipe` 呢？

**Comment by nie55352177** [comment]
原来有专门的模块啊，我一直不知道有这个`CellModule `。thanks
