### ISSUE TITLE
日期插件，在组件中设置 ngModel 变量的值，页面无法改变.

### ISSUE THREAD

**Issue by enyyongyang** [cipchk/ngx-weui#19]
看源码，发现    <input type=\"text\" class=\"weui-input\" value=\"{{_text}}\"
这个_text 是插件点击了，才能设置的。

能改成 ngModel   组件改变了，页面就改变吗？

看了2小时。（气的我心脏病都犯了。）

**Comment by cipchk** [comment]
抱歉，我没明白你的意思。

**Comment by enyyongyang** [comment]
<weui-date-picker
        placeholder="选择日期"
                        [(ngModel)]="testDate" name="date"
      ></weui-date-picker>

**Comment by enyyongyang** [comment]
<weui-date-picker
        placeholder="选择日期"
                        [(ngModel)]="testDate" name="date"
      ></weui-date-picker>

**Comment by enyyongyang** [comment]
<weui-date-picker
        placeholder="选择日期"
                        [(ngModel)]="testDate" name="date"
      ></weui-date-picker>
------
  ngOnInit() {
    this.testDate = new Date("2011-11-22");
}
------
用组件的，设置一个初始值，但是页面的input 是空的， 

我现在暂时改用服务调用吧、你有时间看看那，就是说  （我在组件里改变了testDate 的值，理论上来说，页面应该显示改变呀，但是现在好像子组件里的值是改变了，但是页面显示没变。）

**Comment by enyyongyang** [comment]
作者大大， 怎么实现日期显示 年月，不要日。（yyyy-MM）

**Comment by cipchk** [comment]
1、`weui-date-picker` 只是一个Picker组件，如果你页面中的其他 `input` 需要，可以自行 `[value]="date"` 即可。

2、日期格式化问题可以使用 `format="yyyy-MM-dd"` 更多参数见[API](https://cipchk.github.io/ngx-weui/#/docs/components/datepicker)

**Comment by enyyongyang** [comment]
this.pickerService.showDateTime("date", "yyyy-MM", 
这样写的话，选择后，确实格式化成 年-月。（但是好像不能弹出选择菜单就只有年-月）

第一个问题（确实，日期插件只是一个组件，还是应该用input，点击唤起他。）

**Comment by cipchk** [comment]
是的，只支持【日期】、【时间】、【日期时间】三类型。
