### ISSUE TITLE
日期组件用服务调用的话。选完后页面底部会显示 日期几秒

### ISSUE THREAD

**Issue by enyyongyang** [cipchk/ngx-weui#20]
这是由于组件里面的input，但是用组件方式的话（这个input 会有用，但是用服务，这个input 没用。）

是不是考虑在服务里把input remove

**Comment by cipchk** [comment]
抱歉，能否做一个GIF吗？我没明白。[DEMO](https://cipchk.github.io/ngx-weui/#/example/picker) 中，并无你说的情况。

**Comment by enyyongyang** [comment]
![Uploading image.png…]()

**Comment by enyyongyang** [comment]
就是，你有时间的话，可以试试。就是
1.把页面节点删的只剩下（用服务调用日期插件的几个按钮）
2.把
.container, .page {
    position: absolute;
    top: 0;
    right: 0;
    /* bottom: 0; */ 注释掉
    left: 0;
}
3.给body上加样式 height:300px;    
上面3步是为了把那个追加的组件露出来。。  这样 ，你选择了点击确定后，会看见那个日期字符串在页面显示了一下。

但是你把  page 这个 div 设置成  上下左右  这样是没有一点BUG 的。

）我也不知道这（服务调用组件，组件显示出来的问题）算不算BUG，应该这个不算bug。

**Comment by cipchk** [comment]
虽然我没有太明白，但是如果是由于你额外加CSS引起的问题，那么你应该从这些CSS中解决这个问题。

**Comment by enyyongyang** [comment]
不是，是官网的demo 是全屏的，所以服务追加的组件看不见，我上面的3个操作是在官网，直接在浏览器操作的。也能出现，这种情况。

**Comment by cipchk** [comment]
恩

**Comment by cipchk** [comment]
if it solves the problem, please close this issue, thx

**Comment by enyyongyang** [comment]
no solves ，就是说用服务调起组件实际上是把组件追加到页面底部。治国不官网的demo 样式是满屏的，所以看不到。（我的样式不是设置的满屏的，所以能看到。）（这个可算可不算BUG吧。）

**Comment by cipchk** [comment]
能否利用 `plnkr` 提供一个在线示例呢？写法[参见](http://embed.plnkr.co/vrb1b6KrhvyqyCFXQ7zg/)。

**Comment by enyyongyang** [comment]
import { PickerData, PickerOptions, PickerService } from 'ngx-weui/picker'
这个怎么导入呀（找不到。怎么引入）
Not found: file "/bundles/ngx-weui.umd.min.js/picker" in package ngx-weui@1.0.9

**Comment by enyyongyang** [comment]
这个写ng插件用什么软件打包的呀，还是有什么教程，工具，我查过好像是发布npm 包，是这样吗。在网上找不到相关的

**Comment by cipchk** [comment]
@enyyongyang 如果你是在我发的基础上改的话，只需要

```typescript
import { PickerData, PickerOptions, PickerService } from 'ngx-weui'
```

因为我默认配置 `ngx-weui` 全部模块一次性导入。

**Comment by enyyongyang** [comment]
https://embed.plnkr.co/CnNsr9Tw53qra6EXL0W8/
