### ISSUE TITLE
swiper不能用

### ISSUE THREAD

**Issue by f89688563** [cipchk/ngx-weui#21]
Can't bind to 'options' since it isn't a known property of 'weui-swiper'.

**Comment by cipchk** [comment]
不好意思，能否提供更多细节！不好意思，能否提供更多细节！

**Comment by f89688563** [comment]
是按照https://cipchk.github.io/ngx-weui/#/docs/components/swiper 这里面的写的
Uncaught Error: Template parse errors:
Can't bind to 'options' since it isn't a known property of 'weui-swiper'.
1. If 'weui-swiper' is an Angular component and it has 'options' input, then verify that it is part of this module.
2. If 'weui-swiper' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("<weui-swiper [ERROR ->][options]="options">

**Comment by cipchk** [comment]
是否导入相应的模块：

`
import { SwiperModule } from 'ngx-weui/swiper';

@NgModule({
    imports: [ SwiperModule.forRoot() ]
})
`

**Comment by f89688563** [comment]
有导入，在app.module.ts

**Comment by cipchk** [comment]
看错误是由于找不到 `weui-swiper` 组件，或许你可以再好好看一下导入是否正确。

**Comment by enyyongyang** [comment]
是模块嵌套的话，只能在组件最近的那个父级模块引入。不能隔着模块引入。

**Comment by cipchk** [comment]
你可以把 `ngx-weui` 相关模块导入到 ShareModule 当中，可以解决这个问题。
