### ISSUE TITLE
日期插件（也算需求吧，有时间再看吧）

### ISSUE THREAD

**Issue by enyyongyang** [cipchk/ngx-weui#22]
（以下两个都是用服务实现的）
1.日期插件快速点击。会出现一个以上的弹出窗
   （这个通过防止表单重复提交，加个变量，也可以处理）
2.日期插件点击后，不点击确定或取消，通过浏览器导航返回上一页。
   会出现弹出层还在的情况
   我用ng1开发的时候。用的其他弹出窗插件也有这个情况，我是在路由监听那块DOM移除的
   看服务没有提供销毁的方法（有的话，在component 的 ngOnDestroy 调用销毁）

**Comment by cipchk** [comment]
`Service` 的确会有这种情况，但是目前也没有好的办法可以避免，因为Service是动态构建组件，而组件的位置在于 `<body>` 最外层，对于后退只会在相应的 `<router-outlet>` 清理对应的组件，倒置其依然存在。

这个问题，包括所有利用Service构建组件都存在（诸如：ActionSheet），只能待我有更好的方案再说了。

**Comment by enyyongyang** [comment]
我觉得可以这样，将这些服务追加的组件不追加到body底部，全部追加到一个固定ID 的容器里，在追加actionsheet 和 picker 时，先清空该容器。（这个容器放在body最下面），有固定ID的话，好操作DOM。

**Comment by cipchk** [comment]
组件有自己的一套生命周期及规则，单纯操作DOM是不可取的。

**Comment by enyyongyang** [comment]
恩，有道理。但是加个ID，方便销毁。初始化也是DOM 呀。销毁方法里面用DOM 。

**Comment by cipchk** [comment]
# 1.0.13

- [增] `weui-actionsheet`、`weui-dialog`、`weui-picker`、`weui-toast`、`weui-toptips` 组件对应的Service类增加 `destroy`、`destroyAll` 方法用于强制销毁组件。

因此，可以参考[actionsheet.component.ts](https://github.com/cipchk/ngx-weui/blob/master/demo/src/app/example/actionsheet/actionsheet.component.ts#L48)来解决当下问题。虽然有点麻烦，但是相对于是安全性销毁。
