### ISSUE TITLE
作者，picker的需求来了。

### ISSUE THREAD

**Issue by enyyongyang** [cipchk/ngx-weui#23]
地区插件能否增加一个显示列数的选项。（需求：一份地区三级数据，但项目中有的用到一级，有的用到2级，有的用到3级。）

日期选择也是，有的我是选择 年-月  还有一个年-月-日-时。
（日期也可以用我显示几列，设置dateTime 后再用列数控制）

**Comment by cipchk** [comment]
可以自行使用 `weui-picker` 构建需要的数据列。
