### ISSUE TITLE
dialog自定义html 无法展示<input>?

### ISSUE THREAD

**Issue by Zero09** [cipchk/ngx-weui#24]
dialog自定义html 无法展示<input>?
this.config.content = ` <p align="left">请输入</p> <input type="text" value="text" />  `  （这里是有加`的）
显示不出 input呢，有没有什么好提议？

**Comment by cipchk** [comment]
应该会显示的，因为内部实际就是使用 `[innerHTML]` 绑定内容的。但 `input` 实际上在 `weui-dialog` 中很难获取到新值。我一直也在考虑是否增加一个 `weui-promp` 组件之类的。

不过，另一种解决办法，你可以使用我另一个 [ngx-bootstrap-modal](https://github.com/cipchk/ngx-bootstrap-modal)` 开源项目，也很简单的解决模态框中表单的问题。

**Comment by cipchk** [comment]
see [1.0.14](https://github.com/cipchk/ngx-weui/blob/master/CHANGELOG.md)
