### ISSUE TITLE
weui-infiniteloader在父容器滚动时无法生效

### ISSUE THREAD

**Issue by lovexurongquan** [cipchk/ngx-weui#25]
微信上使用上啦下拉有时出现黑边  此时weui-infiniteloader滚动就会失效。

**Comment by lovexurongquan** [comment]
是否有办法固定不允许黑边出现。

**Comment by cipchk** [comment]
抱歉，我没有办法重现，能否弄一个可重现的 plnkr.co demo呢？或使用gifcam录制一份gif上传呢，谢谢。

**Comment by lovexurongquan** [comment]
![image](https://user-images.githubusercontent.com/6656853/29173882-36332516-7e17-11e7-9152-dcc56b28400b.png)
请扫描此二维码。谢谢。

**Comment by lovexurongquan** [comment]
body {
  position: fixed;
}

body>* {
  position: fixed;
}
我加上俩样式  下拉和上拉就不出黑边了  不过不知道会不会出现其他问题。。。

**Comment by lovexurongquan** [comment]
不行  还是不行  使用苹果手机微信  扫描官网的 https://cipchk.github.io/ngx-weui/#/example/infiniteloader 也会出现下面黑边出现  导致无法触发加载方法。

**Comment by cipchk** [comment]
出现黑边应该是由于原生滚动条引起的，这一点的确没有在 prt 、infiniteloader 中考虑进来，其实从移动端的角度来讲，是应该考虑进来的，我会在周末做一下细节 上的调整。

**Comment by neesonqk** [comment]
我也遇到了类似的问题。

重现：
1. 一个页面滚动到最底部后等待1-2秒
2. 快速继续向上滚动几下后立刻再向上回滚

这时候页面会卡住不动了，要等待几秒钟后才可以滚动。

附件是一个简单的测试工程。

[Archive.zip](https://github.com/cipchk/ngx-weui/files/1262756/Archive.zip)

**Comment by neesonqk** [comment]
这个问题有大概的修复时间吗？谢谢！

**Comment by cipchk** [comment]
我尽快的修复此问题，因为这段时间工作太忙了。

**Comment by cipchk** [comment]
Release [1.0.15](https://github.com/cipchk/ngx-weui/blob/master/CHANGELOG.md) ，调整了一个细节。

之前节流是 `300ms` 的确会出现 @neesonqk 的问题，因此，我调整至 `100ms` 效果改善非常多，所以可以手动去调整节流值去改善这个问题。

**Comment by neesonqk** [comment]
这个问题貌似还是有的，我自己调整到0问题还存在，另外1.0.15可以推到npm吗？

**Comment by cipchk** [comment]
@neesonqk 抱歉。npm版本已更新，我本地设置 `nrm` 指向 taobao，倒置推送失败，我竟然没有发现。

是否参考一下 [tabbar](https://cipchk.github.io/ngx-weui/#/example/tabbar) & [infiniteloader](https://cipchk.github.io/ngx-weui/#/example/infiniteloader) 示例，是否能解决问题吗？说实在你的附件我并没有运行起来。

是否能在基于这修片本的 [plnkr](http://embed.plnkr.co/vrb1b6KrhvyqyCFXQ7zg/) 重现一次现状呢？

**Comment by neesonqk** [comment]
@cipchk 谢谢。附件我看一下什么问题。

**Comment by neesonqk** [comment]
[Archive.zip](https://github.com/cipchk/ngx-weui/files/1275799/Archive.zip)

不好意思，工程打包的时候一个隐藏文件没有拷贝进去。现在可以运行了。

1. npm install
2. ng serve --host your-ip-add-ress

感谢！

**Comment by neesonqk** [comment]
@cipchk 另外我说的这个问题貌似只有手机浏览的时候才可以重现。
