### ISSUE TITLE
微信js认证失败，这里是项目没完善，还是本地需要其他什么配置？

### ISSUE THREAD

**Issue by MicroLord** [cipchk/ngx-weui#27]
GET https://cipchk.github.io/wx-config 404 ()

**Comment by cipchk** [comment]
是的。

只包含以下两项：

+ 完整 js-sdk 的声明文件。（TS在打包时对于声明文件无法处理，因此，你可以直接COPY该.d.ts文件至项目中，或者寻找其它方案）
+ 懒加载 **jweixin-1.2.0.js** 文件。

除此之外，没有别的了。

**Comment by MicroLord** [comment]
👌
