### ISSUE TITLE
Can't bind to 'subTitle' since it isn't a known property of 'Page'.

### ISSUE THREAD

**Issue by neesonqk** [cipchk/ngx-weui#29]
While installed ngx-weui with `npm install ngx-weui --save`, Page component is missing out from the package. Then when I use it as a component in other components, it throws `Can't bind to 'subTitle' since it isn't a known property of 'Page'.` exception.

![image](https://user-images.githubusercontent.com/7279067/29801938-e321900a-8ca4-11e7-9226-c509f405561d.png)

![image](https://user-images.githubusercontent.com/7279067/29801944-eac72342-8ca4-11e7-8d3d-37265e01c5c6.png)

**Comment by liuliangjia** [comment]
这个问题是怎么解决的？我也是这样，page组件在哪儿？

**Comment by neesonqk** [comment]
这个组件是demo中的 你可以从它demo的例子中把Page组件拷贝出来用
