### ISSUE TITLE
Uploader

### ISSUE THREAD

**Issue by lovexurongquan** [cipchk/ngx-weui#30]
我有一个Component 里面有个属性叫model，调用Uploader时我想将这个model的某个属性放到params中传到后台，但是在UploaderOptions里面访问不到这个model属性，请问该如何才能访问到这个model属性的值呢。。

**Comment by lovexurongquan** [comment]
在onUploadComplete里面我想获取后台返回的参数也无法设置到这个model属性上。。

**Comment by lovexurongquan** [comment]
使用了另一种方式调用，属性可以访问了。
![image](https://user-images.githubusercontent.com/6656853/29867955-c5e9d8a6-8daf-11e7-9cf8-896eeea4c8d8.png)
但是感觉不是很好，是不是有其他解决办法。

**Comment by lovexurongquan** [comment]
问题解决了，不过希望在文件对象 FileItem实体上加一个字段，用来保存服务器返回参数的，最后页面其他数据提交数据时候，从这个字段上再去取数据。
![image](https://user-images.githubusercontent.com/6656853/29870247-2a84b4e4-8db9-11e7-8008-20657473826e.png)
![image](https://user-images.githubusercontent.com/6656853/29870249-3045d142-8db9-11e7-96c1-b124b5729cd0.png)

**Comment by cipchk** [comment]
可以利用 Uploader 本身的事件，将需要的数据保存在组件类当中。`FileItem` 本身是存储上传过程中所需要的业务数据。
