### ISSUE TITLE
什么时候可以出一个支持到镇街的组件，city-picker 只支持到区级

### ISSUE THREAD

**Issue by lynings** [cipchk/ngx-weui#31]
```
export class CityPickerComponent implements ControlValueAccessor, OnDestroy {
...
writeValue(value: any): void {
        if (value) {
            this._value = value;
            if (this._value && this._value.length === 6) {
                this.valueToSelect(this._tmpData, this.dataMap.items, 1);
                this.parseData(this._tmpData, this.dataMap.items, this._selected);
            }
        }
    }
...
}
```
街镇级类似： 440605011000 十二位数。
---------------------------------------
已提交一个 pull request，请看看符不符合您的代码设计。

**Comment by cipchk** [comment]
谢谢！

目前 `weui-city-picker` 的定位是省、市、区县，并依赖国家标准的行政区代码规则。

而镇街级的确在电商需求上会很比较多，但是由于没有异步加载的方法，这个数据量会非常庞大，因此个人比较不建议在此基础增加至4列。

如若有需求可以，在 `weui-city-picker` 作为所在地选择，城镇可以额外另一个 `picker` 中完成，这一点非常容易做到，只需要配合 `(change)` 即可。

**Comment by lynings** [comment]
@cipchk 您好，如果支持异步的话，是否就可以加上这个功能？

**Comment by cipchk** [comment]
我会写上相应的DEMO示例，但应该不会做为 `ngx-weui` 组件库之一。

原因是，倘若直接异步加载，只需要配合 `weui-picker` 组件就非常容易实现。

**Comment by lynings** [comment]
@cipchk 好的，thx
