### ISSUE TITLE
win10 下 npm start 报错

### ISSUE THREAD

**Issue by dusdong** [cipchk/ngx-weui#35]
1、**npm install** 会有以下提示：
`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN ng2-checklist@1.0.2 requires a peer of @angular/core@2.0.0-rc.1 but none was installed.
npm WARN ngx-gesture-password@1.0.0 requires a peer of @angular/common@4.0.1 but none was installed.
npm WARN ngx-gesture-password@1.0.0 requires a peer of @angular/core@4.0.1 but none was installed.
npm WARN ngx-highlight-js@1.0.1 requires a peer of @angular/core@4.0.1 but none was installed.
npm WARN ngx-notify@1.0.1 requires a peer of @angular/compiler@4.0.1 but none was installed.
`

2、**npm start** 会有以下提示：
`
> ngx-weui@1.0.15 start F:\Framework_Angular2\ngx-weui
> ng serve --aot --host 0.0.0.0

** NG Live Development Server is listening on 0.0.0.0:4200, open your browser on http://localhost:4200 **
Date: 2017-09-03T22:45:10.110Z
Hash: a4971ddc81d82022fa14
Time: 7344ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 8.7 kB {vendor} [initial] [rendered]
chunk {scripts} scripts.bundle.js, scripts.bundle.js.map (scripts) 328 kB {inline} [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 31.6 kB {inline} [initial] [rendered]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 1.54 MB [initial] [rendered]

ERROR in Error encountered resolving symbol values statically. Could not resolve ngx-weui relative to F:/Framework_Angular2/ngx-weui/demo/src/app/shared/shared.module.ts., resolving sym
bol SharedModule in F:/Framework_Angular2/ngx-weui/demo/src/app/shared/shared.module.ts, resolving symbol SharedModule in F:/Framework_Angular2/ngx-weui/demo/src/app/shared/shared.modul
e.ts, resolving symbol SharedModule in F:/Framework_Angular2/ngx-weui/demo/src/app/shared/shared.module.ts
ERROR in ./demo/src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'F:\Framework_Angular2\ngx-weui\demo\src'
resolve './$$_gendir/app/app.module.ngfactory' in 'F:\Framework_Angular2\ngx-weui\demo\src'
  using description file: F:\Framework_Angular2\ngx-weui\package.json (relative path: ./demo/src)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: F:\Framework_Angular2\ngx-weui\package.json (relative path: ./demo/src)
    using description file: F:\Framework_Angular2\ngx-weui\package.json (relative path: ./demo/src/$$_gendir/app/app.module.ngfactory)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        F:\Framework_Angular2\ngx-weui\demo\src\$$_gendir\app\app.module.ngfactory doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        F:\Framework_Angular2\ngx-weui\demo\src\$$_gendir\app\app.module.ngfactory.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        F:\Framework_Angular2\ngx-weui\demo\src\$$_gendir\app\app.module.ngfactory.js doesn't exist
      as directory
        F:\Framework_Angular2\ngx-weui\demo\src\$$_gendir\app\app.module.ngfactory doesn't exist
[F:\Framework_Angular2\ngx-weui\demo\src\$$_gendir\app\app.module.ngfactory]
[F:\Framework_Angular2\ngx-weui\demo\src\$$_gendir\app\app.module.ngfactory.ts]
[F:\Framework_Angular2\ngx-weui\demo\src\$$_gendir\app\app.module.ngfactory.js]
[F:\Framework_Angular2\ngx-weui\demo\src\$$_gendir\app\app.module.ngfactory]
 @ ./demo/src/main.ts 4:0-74
 @ multi webpack-dev-server/client?http://localhost:4200 ./demo/src/main.ts

webpack: Failed to compile.
`
请问下该怎么解决？谢谢

**Comment by cipchk** [comment]
`ngx-weui` 有两个应用，因此，若你是本地构建的话，需要先构建 `ngx-weui` 模块，即：

```bash
npm run build
```

接着与 `demo` 进行关联：

```bash
npm run link
```

最后，才运行 `demo`。

```bash
npm run demo.serve
```

**Comment by dusdong** [comment]
已运行成功，谢谢~
