### ISSUE TITLE
[weui-checklist]怎么获取选中的checkbox的值

### ISSUE THREAD

**Issue by JCqiu** [cipchk/ngx-weui#37]
文档上没有对[weui-checklist]这个api进行详细的说明

**Comment by cipchk** [comment]
参考DEMO写法 [HTML](https://github.com/cipchk/ngx-weui/blob/master/demo/src/app/example/input/input.component.html#L25) & [TS](https://github.com/cipchk/ngx-weui/blob/master/demo/src/app/example/input/input.component.ts#L28)
