### ISSUE TITLE
swipter 的分页器不显示

### ISSUE THREAD

**Issue by ForrestGumpForever** [cipchk/ngx-weui#38]
swipter 的分页器不显示

**Comment by cipchk** [comment]
抱歉，请提供更多的信息。或参考[demo](https://cipchk.github.io/ngx-weui/#/docs/components/swiper)

**Comment by ForrestGumpForever** [comment]
![image](https://user-images.githubusercontent.com/15998062/30417945-f3d9d1a2-9963-11e7-8c60-638fe4822eeb.png)
就是按照 官网的demo 来编写的，swiper-pagination 下的 子dom 都没有生成！
ts:
![image](https://user-images.githubusercontent.com/15998062/30418061-52301f40-9964-11e7-86a9-ff9191ca3ab4.png)
scss:
![image](https://user-images.githubusercontent.com/15998062/30418082-5f3d016c-9964-11e7-8fc3-4846475ad60c.png)
html:
![image](https://user-images.githubusercontent.com/15998062/30418097-6747c680-9964-11e7-9f11-9061c1954fa3.png)
result:
![image](https://user-images.githubusercontent.com/15998062/30418214-d060626c-9964-11e7-949c-e56af5a38dfb.png)

**Comment by cipchk** [comment]
的确很奇怪，你可以尝试给 `FindComponent` 加上 `encapsulation: ViewEncapsulation.None` 看是否是因为样式的关系，倒置 Swiper 初始化受影响了。

**Comment by ForrestGumpForever** [comment]
真的很奇怪，我什么都么有做 ，现在出现了，分页器（滑动的小圆点），但是 我发现了另外的问题，
请看一下 [https://github.com/cipchk/ngx-weui/issues/39](url)
