### ISSUE TITLE
swiper 手机端无法滑动

### ISSUE THREAD

**Issue by ForrestGumpForever** [cipchk/ngx-weui#39]
swiper 手机端无法滑动，显示的是最后一个slide-item:
场景描述：在使用 weui-tabbar 时
![image](https://user-images.githubusercontent.com/15998062/30420931-b82883f6-996d-11e7-99d7-c1c308ec7ee8.png)

第一个 weui-tab 的 weui-swiper 正常使用，第二个 就会出现 无法滑动，只显示出 最后一个 slide-item

**Comment by cipchk** [comment]
你可以通过尝试访问 [DEMO](https://cipchk.github.io/ngx-weui/#/example/swiper)，`ngx-weui` 本身并没有针对 `Swiper` 进行过度封装，若是兼容性问题可以从 `Swiper` 去寻找问题原因。

**Comment by ForrestGumpForever** [comment]
![image](https://user-images.githubusercontent.com/15998062/30423112-72eb3430-9974-11e7-8155-7b66b76fb3b2.png)
![image](https://user-images.githubusercontent.com/15998062/30423138-8be0e958-9974-11e7-91f2-2039f2934635.png)
属性 active 到底 有什么作用？

**Comment by cipchk** [comment]
选项卡的选中状态
