### ISSUE TITLE
weui-infiniteloader  数据加载完后 ，头部的 顶部的导航 定位无效了！

### ISSUE THREAD

**Issue by ForrestGumpForever** [cipchk/ngx-weui#40]
![image](https://user-images.githubusercontent.com/15998062/30527089-2d830482-9c57-11e7-96f8-c80e03a6b194.png)
![image](https://user-images.githubusercontent.com/15998062/30527106-79b94046-9c57-11e7-9607-84c9415d038d.png)
![image](https://user-images.githubusercontent.com/15998062/30527118-93357396-9c57-11e7-9a61-906eb8003734.png)

**Comment by ForrestGumpForever** [comment]
加了 height="85vh" ，控制了 container ! 个人感觉API 不是很清晰！

**Comment by cipchk** [comment]
@ForrestGumpForever 非常抱歉，API文档都是由代码生成的，工作太忙了，没办法加强这一块，我会加上相应的规则，希望大家帮忙PR文档的改善。

**Comment by ForrestGumpForever** [comment]
<weui-infiniteloader (loadmore)="onLoadMore($event)" height="85vh">
在浏览器里看到的却是
<weui-infiniteloader height="85vh" class="weui-infiniteloader" style="height: 100vh;">

**Comment by cipchk** [comment]
`weui-infiniteloader` 需要一个基体的高度以确保有效计算，我倒建议你修改 `.dynamic-container` 的 `margin` 值，让 `weui-infiniteloader` 保持在整个可视区域当中，这个时候你就无须管其高度的问题了。

**Comment by ForrestGumpForever** [comment]
你的提议不错，但是我还是想知道，height 要怎么设置才有效！

**Comment by cipchk** [comment]
`weui-infiniteloader` 说白了需要一个容器，然后当滚动至该容器的 `percent` 比例时触发 `loadmore` 事件，仅此而已。

**Comment by ForrestGumpForever** [comment]
{
      provide: InfiniteLoaderConfig, useFactory: () => {
      return Object.assign(new InfiniteLoaderConfig(), {height: '85vh'});
    }
    }
已搞定，刚才 出现了其他问题 ，导致配置没有生效，还以为 这样配有错呢！
