### ISSUE TITLE
添加 自定义 InfiniteLoaderConfig 后不能 compile

### ISSUE THREAD

**Issue by ForrestGumpForever** [cipchk/ngx-weui#41]
![image](https://user-images.githubusercontent.com/15998062/30530404-0fcb7272-9c79-11e7-9643-dafaad854f4d.png)
执行 ng serve 前 ，加上就报错
 
![image](https://user-images.githubusercontent.com/15998062/30530435-39bc52c2-9c79-11e7-8979-7da72d026757.png)
去掉后，在执行 ng serve ,启动后,加上 就正常运行！

**Comment by cipchk** [comment]
抱歉，我无法重现这个问题呢！

**Comment by ForrestGumpForever** [comment]
我已经解决了，推荐你看一下这个文档，https://github.com/rangle/angular-2-aot-sandbox#arrow-function-exports-top！

**Comment by cipchk** [comment]
@ForrestGumpForever 能否具体说明一下解决方法，这样有同样问题的人可以做参考。谢谢。
