### ISSUE TITLE
subcribe 的  Popup ,怎么实现，文档 写的不是很明白！

### ISSUE THREAD

**Issue by ForrestGumpForever** [cipchk/ngx-weui#42]
![image](https://user-images.githubusercontent.com/15998062/30583519-ddbd99a4-9d59-11e7-8ab9-2d2cb61e117a.png)
支持订阅 subscribe 且 全屏后的 Popup 找不到了 确认,取消按钮，Demo 中 也不是很详细的说明 支持subscribe 的 popup 怎么实现的，请指教！

**Comment by cipchk** [comment]
```html
<weui-popup #full [config]="{is_full: true}">
    <button class="weui-btn weui-btn_primary" (click)="full.close()">Close Popup</button>
</weui-popup>
```

`[config]` 见API文档。

![tim 20170919171113](https://user-images.githubusercontent.com/2987467/30584841-9ffd50ec-9d5d-11e7-992c-69e0a8ef825e.png)

订阅方式DEMO中也有相应代码：

```typescript
    onSub() {
        this.subPopup.show().subscribe((res: boolean) => {
            alert('click confirm!!!');
        });
    }
```
