### ISSUE TITLE
关于 textarea 在focus 时，手机键盘出现，textarea 消失问题

### ISSUE THREAD

**Issue by ForrestGumpForever** [cipchk/ngx-weui#43]
textarea 在focus 时，手机键盘出现，textarea 消失，好像时被挤上去了！
![image](https://user-images.githubusercontent.com/15998062/30587533-1174aad8-9d66-11e7-944f-768867c07e13.png)
![image](https://user-images.githubusercontent.com/15998062/30587905-5a4c4076-9d67-11e7-94b7-96652e6bc0df.png)

**Comment by cipchk** [comment]
这个问题不属于 `ngx-weui` 的范涛，这有一篇[文章](https://www.zhihu.com/question/32746176)你可以从中得到解决方案。
