### ISSUE TITLE
weui-input 验证机制问题

### ISSUE THREAD

**Issue by ForrestGumpForever** [cipchk/ngx-weui#45]
刚打开页面就开始验证 出现错误信息，体验很不好！我看了API 不知道怎么去处理！
![image](https://user-images.githubusercontent.com/15998062/30840015-8bcd5500-a2a7-11e7-8dc1-a461473daac4.png)
正则表达式，也无效！

**Comment by cipchk** [comment]
Angular 内置校验，这些参数还包括：

+ `required`
+ `minlength`
+ `maxlength`
+ `pattern`

**Comment by ForrestGumpForever** [comment]
我知道 angular 有这些内置校验，我说的是ngx-weui 中 weui-input 等校验无效

**Comment by cipchk** [comment]
可以参考API文档，正则并不是这么用的：

```html
<input weui-regex weui-regex="^\w+$">
```

**Comment by jonashao** [comment]
页面一打开就做了校验的问题请问应该怎么解决？
[文档中的例子](https://cipchk.github.io/ngx-weui/#/components/input)也有同样的问题
![image](https://user-images.githubusercontent.com/7600440/41419724-4aeab2de-7025-11e8-917d-a71040cfa6a1.png)
现状：用户在未填写表单的时候，表单中必填的字段就已经变红了，
期望的是：用户填写完毕后再校验表单，表单dirty之后应不显示错误信息。
