### ISSUE TITLE
mask遮罩层问题，很急，在线等！！

### ISSUE THREAD

**Issue by nie55352177** [cipchk/ngx-weui#47]
ActionSheet、Sidebar、Popup等使用到mask遮罩层的组件遮罩层不显示。demo也是一样

**Comment by cipchk** [comment]
抱歉，不明白你的意思。

**Comment by nie55352177** [comment]
之前ActionSheet显示时空白处是显示遮罩层的，现在没有显示了。上述组件也都没有显示了

**Comment by nie55352177** [comment]
如果没有遮罩层，backdrop这个属性就没有意义了

**Comment by nie55352177** [comment]
https://cipchk.github.io/ngx-weui/#/docs/components/actionsheet   你可以自己看一下demo

**Comment by ForrestGumpForever** [comment]
在 actionsheet demo  这个页面，刷新一下页面，就正常了！

**Comment by cipchk** [comment]
![tim 20171008161929](https://user-images.githubusercontent.com/2987467/31315128-7d8fd58e-ac44-11e7-91c9-fe116f248759.png)

**Comment by nie55352177** [comment]
我也不知道为什么跟官网demo不一样，我是npm install ngx-weui 下载的1.0.15版本。我在源码里加上visibility: 'visible'就正常了
![qq 20171008171311](https://user-images.githubusercontent.com/16702082/31315480-1ff86d84-ac4c-11e7-80a4-cdb532e11c4c.jpg)

**Comment by nie55352177** [comment]
使用MaskModule会影响其他依赖遮罩层的组件显示遮罩

**Comment by cipchk** [comment]
麻烦提供一个复现的在线演示（http://plnkr.co/edit/tpl:vrb1b6KrhvyqyCFXQ7zg）
