### ISSUE TITLE
weui-sidebar中的 closed 不触发，closeStart 会触发两次！

### ISSUE THREAD

**Issue by ForrestGumpForever** [cipchk/ngx-weui#48]
weui-sidebar中的 closed 不触发，closeStart 会触发两次！

**Comment by ForrestGumpForever** [comment]
![image](https://user-images.githubusercontent.com/15998062/31314504-f7c5f46a-ac34-11e7-9d80-622c3589fdef.png)
![image](https://user-images.githubusercontent.com/15998062/31314518-77b75448-ac35-11e7-80ed-d0812180b8d7.png)

**Comment by cipchk** [comment]
请确认你的 `onCloseStart` `onClosed` 的打印内容。

**Comment by ForrestGumpForever** [comment]
onCloseStart----> console.log("close start");
onClosed----> console.log("closed");

**Comment by cipchk** [comment]
thanks, i will check this issue.
