### ISSUE TITLE
About Toast component

### ISSUE THREAD

**Issue by neesonqk** [cipchk/ngx-weui#49]
How do I close a toast manually rather than a timeout setting? What I want is to close a toast with the type of loading only after my api call, then I'm able to coordinate api response and UI updating, I don't find a `close` method from your document, please advice, thank you!

![image](https://user-images.githubusercontent.com/7279067/31478056-2e118b3e-af40-11e7-94ac-1bad027b7126.png)

**Comment by cipchk** [comment]
not supported yet.

**Comment by neesonqk** [comment]
I'd like to complete this feature if possible.

**Comment by cipchk** [comment]
will be feature in next version.
