### ISSUE TITLE
How do I add context to "Mask" component

### ISSUE THREAD

**Issue by neesonqk** [cipchk/ngx-weui#50]
As follow:

![image](https://user-images.githubusercontent.com/7279067/31479297-cf1219ba-af48-11e7-8dec-0f41f6d038a2.png)

**Comment by cipchk** [comment]
the component just provide a mask layer, like:

```html
<weui-mask></weui-mask>
<div>you html</div>
```

you can using toast component if need loading effect.

**Comment by neesonqk** [comment]
My purpose is to display a `message` above this masker, your suggestion doesn't seem to work at all, my code is something like this:

```html
<weui-mask #mask></weui-mask>
<div style="width: 100px; height: 300px; background: red; color: white;">Foo HTML</div>
```
As I applied a `DIV` to the bottom of `weui-mask` following your instructions, however, I cannot see anything appeared but the masker itself.

**Comment by neesonqk** [comment]
Sorry my bad, I misunderstood your explanation as the implementation, you meant that this component doesn't support adding any context above it correct?

**Comment by cipchk** [comment]
a online [demo](http://plnkr.co/edit/38ORgo4mxCGEgXbDLEaJ?p=preview).

but, i don't think it's good, maybe best practise:

```html
<weui-mask>
content
</weui-mask>
```

i will upgrade `weui-mask` component, thx.
