### ISSUE TITLE
ngx-weui 的兼容性如何？

### ISSUE THREAD

**Issue by ForrestGumpForever** [cipchk/ngx-weui#51]
在 ios safari 上测试OK，在android 的 browser 上测试，有问题！想问一下，ngx-weui 的兼容性如何！

**Comment by cipchk** [comment]
equivalent [weui](https://github.com/Tencent/weui) browser compatibilities.

**Comment by ForrestGumpForever** [comment]
一个非常简单的页面，iOS 打开非常快，不到1秒，可是 android 浏览器打开 就要10s!

**Comment by cipchk** [comment]
can you works in the android machine? or just open slow? they are different.

try open [examples](https://cipchk.github.io/ngx-weui/#/example) page in android.

i can help you, but you need provide me with more information.
