### ISSUE TITLE
weui-tabbar 下 的 weui-tab 初始化导致 swiper失效。

### ISSUE THREAD

**Issue by ForrestGumpForever** [cipchk/ngx-weui#53]
weui-tabbar 下 的 weui-tab 初始化导致 swiper失效：
app.component.html:
![image](https://user-images.githubusercontent.com/15998062/31587941-324c9bc8-b21d-11e7-81d9-cfea140e5080.png)
app.component.ts:
![image](https://user-images.githubusercontent.com/15998062/31587944-48bcbc62-b21d-11e7-92ae-204fa1d5bebb.png)
把两个 swiper 分别放在第一个 weui-tab 和 第二个 weui-tab，如果默认初始化激活的是第一个weui-tab 则 第一个的 swiper 正常，第二个swiper 不正常。如果给第二个weui-tab 加上 [active]='true',是默认激活的是 第二个weui-tab 则第二个swiper 正常，第一个swiper 不正常！

**Comment by cipchk** [comment]
我想应该是由于 `swiper` 初始化时无法正确的获取到元素高度之类的引起的吧，你可以试着监听 `weui-tab` 的 `select` 然后才初始化 `swiper`。
