### ISSUE TITLE
NavBar 报错！

### ISSUE THREAD

**Issue by hzb1** [cipchk/ngx-weui#54]
Error: Uncaught (in promise): Error: Template parse errors:
'weui-tab' is not a known element:
1. If 'weui-tab' is an Angular component, then verify that it is part of this module.
2. If 'weui-tab' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

**Comment by cipchk** [comment]
Import the `ngx-weui` in to your root `AppModule`.
