### ISSUE TITLE
InfiniteLoaderComponent 组件本次滚动结束后无法重新开始。

### ISSUE THREAD

**Issue by Awheat** [cipchk/ngx-weui#55]
您好 ， 本地安装的npm包中的infiniteloader组件中， 这个文件infiniteloader.component.js中的InfiniteLoaderComponent原型上缺少restart()函数，  因为看着demo中的API中有这样的一个方法 ， 但是在使用中就报错restart() undefined, 于是我自己在上面文件中InfiniteLoaderComponent的原型上添加了一个restart() 就可以用了。

**Comment by cipchk** [comment]
确认一下你的版本，并重新安装依赖包。
