### ISSUE TITLE
添加了agx-weui模块后，angular服务启动报错

### ISSUE THREAD

**Issue by zj12590** [cipchk/ngx-weui#57]
ERROR in Metadata version mismatch for module E:/workSpace/study/ngx-weui/node_modules/ngx-weui/actionsheet/index.d.ts, found version 4, expected 3, resolving symbol Ap
pModule in E:/workSpace/study/ngx-weui/src/app/app.module.ts, resolving symbol AppModule in E:/workSpace/study/ngx-weui/src/app/app.module.ts, resolving symbol AppModul
e in E:/workSpace/study/ngx-weui/src/app/app.module.ts

以上是报的错误信息，说是元数据版本不匹配，望指教

**Comment by cipchk** [comment]
`1.2.x` 以后只支持Angular5，你可以使用 `1.1.x` 之前的版本

**Comment by zj12590** [comment]
我在哪里可以看到ngx-weui的版本信息

**Comment by cipchk** [comment]
`npm view ngx-weui versions`
