### ISSUE TITLE
安装了插件再启动angular4  报Uncaught reflect-metadata shim is required when using class decorators

### ISSUE THREAD

**Issue by zf329398320** [cipchk/ngx-weui#58]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

ngx-weui version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by cipchk** [comment]
`ngx-weui` 最新版本 `1.2.x` 是基于Angular5的，因此恐怕如果是还依然是 Angular4 的话，可以尝试使用 `1.1.x` 之前的版本。
