### ISSUE TITLE
weui-picker

### ISSUE THREAD

**Issue by nie55352177** [cipchk/ngx-weui#6]
如果是多列数据（2列以上），[defaultSelect] 和 [(ngModel)]共存的话有点问题。
[defaultSelect] 以这样的格式（`[defaultSelect]=“[[5],[9]]”`）来控制两列数据默认选中是没有问题，只是input不会把选中的值展示出来；
![qq 20170620093521](https://user-images.githubusercontent.com/16702082/27312943-e2182b58-559d-11e7-929e-d053072e257d.jpg)

 [(ngModel)] 绑定值是最后一列的选中值。input是把值显示出来了，但并不是预期的结果。

![qq 20170620093705](https://user-images.githubusercontent.com/16702082/27312952-ea214bae-559d-11e7-8c17-827672acbe6f.jpg)

可能通过调整数据格式可以达到我的目的？

data:
```
[
 [
  {label: '1', value: 1},
  {label: '2', value: 2},
  {label: '3', value: 3},
              ...
 ],
 [
  {label: '1', value: 1},
  {label: '2', value: 2},
  {label: '3', value: 3},
             ...
 ]
]
```

**Comment by cipchk** [comment]
从picker的角度出发，`[(ngModel)]` 最后一列的值这是对的。

然……

对于，像你这样需要同时获得多列的值，很明显 `[(ngModel)]` 并不合理；且 `[(ngModel)]` 也不是必须的，故类似这种，我建议使用 `(change)` 监听结果；它会返回每一列实际选中的值。

以上，跟是否需要增加 `defaultSelected` 属性并无任何冲突。

**Comment by nie55352177** [comment]
我还不太明白。假如默认显示20岁-25岁。如果`[(ngModel)]=“25”`，在显示picker的时候就会默认选中第一列value为25的项，第二列value为25的项，`[defaultSelect]="[[5],[9]]"`好像并没有起作用。

如果不使用[(ngModel)]，[defaultSelect]确实起作用了，但是页面input并没有显示默认选中的值。
谢谢

**Comment by cipchk** [comment]
`defaultSelect` 接收类型 `number[]` 的一维数组。

我有必要对文档进行更详细，哎，时间好少呀。

**Comment by cipchk** [comment]
我先关闭，如再有疑问，可以重新打开。
