### ISSUE TITLE
Tabbar的滚动条是在哪个div上？

### ISSUE THREAD

**Issue by neesonqk** [cipchk/ngx-weui#60]
使用`TabbarComponent`的时候（注: 不使用`weui-infiniteloader`）如果内容长过手机的高度就会有滚动条, 现在我们有个（图片懒加载）需求需要监听这个滚动事件，尝试了各个嵌套的div都没能截获这个事件，请问具体是哪个div在滚动呢？

谢谢。

**Comment by cipchk** [comment]
tab 内容区域在：

```html
<div class="weui-tab__panel"><ng-content></ng-content></div>
```

[source](https://github.com/cipchk/ngx-weui/blob/master/src/tab/tabbar.component.ts#L10)

**Comment by QiZZ121** [comment]
最新的npm安装上 没有page组件 不是已经是1.2.2版了吗

**Comment by cipchk** [comment]
@QiZZ121 `page` 组件是DEMO所需要的，并不是 `ngx-weui` 组件之一。

**Comment by QiZZ121** [comment]
> ActionSheetComponent.html:2 ERROR Error: Found the synthetic property @visibility. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.

对不起 打扰下 可以帮我看看这个错误怎么解决 我在用到`ActionSheet`的时候出现的 找了好久

**Comment by cipchk** [comment]
@QiZZ121 需要导入 `BrowserAnimationsModule` 模块，`ngx-weui` 组件有大量的动画，这个模块是必须的。

**Comment by QiZZ121** [comment]
@cipchk 可是没有啊 在node-modules里

**Comment by QiZZ121** [comment]
@cipchk 是我安装问题吗

**Comment by QiZZ121** [comment]
@cipchk  对不起 是我智障了 打扰了 谢谢
