### ISSUE TITLE
你好，我是新手angular4.2.4 使用ngx-weui报错怎么解决

### ISSUE THREAD

**Issue by dor-sey** [cipchk/ngx-weui#62]
` "dependencies": {
        "@angular/animations": "^4.2.4",
        "@angular/common": "^4.2.4",
        "@angular/compiler": "^4.2.4",
        "@angular/core": "^4.2.4",
        "@angular/forms": "^4.2.4",
        "@angular/http": "^4.2.4",
        "@angular/platform-browser": "^4.2.4",
        "@angular/platform-browser-dynamic": "^4.2.4",
        "@angular/router": "^4.2.4",
        "core-js": "^2.4.1",
        "ngx-weui": "^1.1.0",
        "rxjs": "^5.4.2",
        "zone.js": "^0.8.14"
    },`
**错误：**
![tim 20171123101600](https://user-images.githubusercontent.com/22736252/33156749-a73c4a5e-d037-11e7-9748-10cbbbcdf726.png)
**代码：**
![tim 20171123101712](https://user-images.githubusercontent.com/22736252/33156751-abde08f4-d037-11e7-842a-37d199f4dbef.png)

**Comment by dor-sey** [comment]
我在click事件中调用没事，这个是必须在事件中触发么

**Comment by cipchk** [comment]
`constructor` 不适合来做这个，你可以在 `ngOnInit` 中执行 `this.srv.show`；
