### ISSUE TITLE
input type="checkbox" 不支持双休数据绑定

### ISSUE THREAD

**Issue by lc01010** [cipchk/ngx-weui#64]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

ngx-weui version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by cipchk** [comment]
抱歉，我没明白你的意思，但 [DEMO](https://cipchk.github.io/ngx-weui/#/example/input) 中是正常的。

**Comment by QiZZ121** [comment]
@lc01010 要双向绑定直接加不就好了吗 ngModel不是吗

**Comment by lc01010** [comment]
<div class="weui-cells__title">复选列表项</div>
        <div class="weui-cells weui-cells_checkbox">
            <label class="weui-cell weui-check__label" for="checkbox-{{i}}"
                *ngFor="let i of checkbox; let index = index">
                <div class="weui-cell__hd">
                    <input type="checkbox" class="weui-check"
                        [weui-checklist]="res.checkbox" name="radio1" [weui-value]="i" id="checkbox-{{i}}">
                    <i class="weui-icon-checked"></i>
                </div>
                <div class="weui-cell__bd">
                    <p>{{i}}</p>
                </div>
            </label>
这个我如何在ts里让它选中或者取消选中
