### ISSUE TITLE
Direct Picker组件在动态取到数据后，无法滚动，点击确认报错

### ISSUE THREAD

**Issue by jointang** [cipchk/ngx-weui#66]
this.reservationService.getReservationMatterSelect().map(options => {
      const list = [];
      options.items.forEach(item => {
        list.push({ label: item.reservationProjectName, value: item.id, disabled: false });
      });
      return list;
    }).subscribe(data => {
      this.reservationMatters.push(data);
    });

**Comment by jointang** [comment]
同事  Html 上 ng-reflect-default-index="NaN"

**Comment by jointang** [comment]
如果使用静态数据   是可以滚动和确认的

**Comment by jointang** [comment]
请问是什么原因导致的，该如何解决？

**Comment by jointang** [comment]
![default](https://user-images.githubusercontent.com/30896083/34194665-bfd51b1e-e594-11e7-8bd7-ed991eeff6f8.png)

**Comment by cipchk** [comment]
烦请提供一个在线重现DEMO，例如：plnkr；否则现在我无法帮你判断。

**Comment by jointang** [comment]
如果我通过angular 路由的Resolver 先加载数据，再加载页面，就不会出现划不动的情况。但是在页面渲染完成之后再请求数据绑定到Direct Picker 上，就会出现划不动的情况。但是有数据绑到Direct Picker。
