### ISSUE TITLE
in apple mobile enterprise wechat left upper back button will bad cause page spoil

### ISSUE THREAD

**Issue by gelibin** [cipchk/ngx-weui#67]
i use abreast of the times ngx-weui + angular4 create project.now , my project is ok for android mobile ,but in apple mobile enterprise wechat when project follow waitApproval page go to detail page and use left upper back button go back ,will  two page cross - display.now i don't know how to solve it. this is bug?
                                          -------------------- i hope you can tell me , thank you

**Comment by cipchk** [comment]
i don't have relevant ENT. WeChat experiences, you need provide substance information to help me judgment.
