### ISSUE TITLE
在页面 OnInit() 钩子中调用 ToastService.Loading() 报 ExpressionChangedAfterItHasBeenCheckedError 错误

### ISSUE THREAD

**Issue by dusdong** [cipchk/ngx-weui#68]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[x] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

在页面 OnInit() 钩子中调用 ToastService.Loading() 会报错：
`ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: 'false'. It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook ?
`
页面打开后，使用 (click) 事件就正常

**Comment by cipchk** [comment]
`ToastService` 调用时会创建组件，因此在 `OnInit` 调用的确会引起 `ExpressionChangedAfterItHasBeenCheckedError`，可以套一个 `setTimeout` 解决这一问题。其实这并非 ngx-weui 的问题，也是 Angular Hook 决定的。

**Comment by dusdong** [comment]
收到！使用 setTimeout() 已解决
