### ISSUE TITLE
关于文件上传问题

### ISSUE THREAD

**Issue by gelibin** [cipchk/ngx-weui#69]
当我点击添加图片功能后，进入到文件夹选择图片，但是我实际上没有选任何图片就返回了，在安卓手机上会在待上传列表上加上一个空白的图片占位，点击查看是黑的。删除后又跟正常删图片一样。ios上正常。这个算是Bug吗，用什么方法能够获取到是否是真实图片选择到待上传列表上。而不是一个占位图片。

**Comment by cipchk** [comment]
能告知具体的版本信息吗？包括：ngx-weui、android 浏览器版本信息等。

**Comment by gelibin** [comment]
ngx-weui版本是1.1.0、android是用企业微信内置浏览器，内核应该都是QQ浏览器内核。貌似android手机都会。测了好几台。

**Comment by cipchk** [comment]
我猜想可能是部分浏览器即使无选择也会触发添加事件，你可以尝试加一个 `filters` 相应的过滤器，应该很容易 解决你的问题；具体细节希望你能把你的 `filters` 提供出来，我好了解实质问题的原因再做修正。先谢谢了。

**Comment by gelibin** [comment]
```
 onFileQueued:(argument: any) =>{
               if(argument.file.size==0 || !argument.file.name){
                this.uploader.removeFromQueue(argument);
               }
            }
```
我在uploaderOptions对象中这样判断，经过测试发现魅蓝手机不会出现那问题了，但是小米的还是会。

**Comment by gelibin** [comment]
小米手机取消后，还是会有size跟name。进不了判断

**Comment by cipchk** [comment]
是否可以通过 `filters` 进行过滤呢？因为这样的方式更友好； `onFileQueued` 一般是用来处理加入后额外的处理。

另外小米手机依然还会提供 `size` & `name` 那是否还有其他可标识的参数呢？
