### ISSUE TITLE
popup内使用weui-date-picker再次初始值问题

### ISSUE THREAD

**Issue by gelibin** [cipchk/ngx-weui#70]
我popup内是一个新增的表单，在表单里有时间控件。当我填完所有内容包括时间后提交表单。再次点开popup框，时间控件上的时间还是有显示，但是没有值绑定到ngModel上，要重新选择时间才行。我现在需要每次点开popup框把控件显示清空。就算我把ngModel删了第二次点开也还是会显示上次选择时间。有什么方法能够每次开打popup框，时间控件值都是空的。```
<weui-date-picker placeholder="请选择时间" [format]="{hu:'',mu:''}" [(ngModel)]="subDate"
                         (change)="addingTimeFormat($event)"
                         name="aPaymentTime" required></weui-date-picker>
``` 在打开弹框的同一个(click)中有加`expenseForm.onReset();`清空表单的功能。

**Comment by cipchk** [comment]
能否提供一个在线plunk可重现示例呢？

**Comment by QiZZ121** [comment]
@cipchk

**Comment by cipchk** [comment]
我会下一版本修复它

**Comment by QiZZ121** [comment]
@cipchk  picker里都有这个问题
