### ISSUE TITLE
swiper4 中的virtual slides无法实现

### ISSUE THREAD

**Issue by baguosiji** [cipchk/ngx-weui#71]
virtual slides 在angular环境下根本无法使用，用js实现不存在这个问题

**Comment by cipchk** [comment]
swiper 本身不会只是一个简单的包装，并未对额外的加工，能否提供一个可重现的在线示例呢？

**Comment by baguosiji** [comment]
http://47.100.15.146/study/  @cipchk

**Comment by baguosiji** [comment]
@cipchk    那是angular的问题？

**Comment by cipchk** [comment]
![a](https://user-images.githubusercontent.com/2987467/34638654-684cd510-f30b-11e7-9955-7b2621d336cd.gif)

我不明白这有什么问题呢？

**Comment by baguosiji** [comment]
往后划一直划注意看当前页面显示 而且我是循环了500条数据

**Comment by cipchk** [comment]
这个我就没办法帮到你了，你可以给我一个可重现的在线示例。

**Comment by baguosiji** [comment]
[slide.zip](https://github.com/cipchk/ngx-weui/files/1610493/slide.zip)
你可以试试这个~

**Comment by baguosiji** [comment]
我用的 weui版本是1.1.0不知道这个有没有影响

**Comment by baguosiji** [comment]
@cipchk    有没有进展呀

**Comment by cipchk** [comment]
的确用原生可以，而且我也没有找出什么原因：

```ts
export class AppComponent implements AfterViewInit {
  ngAfterViewInit(): void {
    var swiper = new Swiper('.swiper-container', this.options);
  }
}
```

**Comment by baguosiji** [comment]
Swiper怎么import进来 还是declare出来？可以详细一点吗？

**Comment by cipchk** [comment]
```ts
declare var Swiper: any;

export class AppComponent implements AfterViewInit {
  ngAfterViewInit(): void {
    var swiper = new Swiper('.swiper-container', this.options);
  }
}
```

**Comment by baguosiji** [comment]
谢啦 大兄弟
