### ISSUE TITLE
DatePicker 配置项中如何用PickerService 配置默认日期及最小日期等

### ISSUE THREAD

**Issue by nieshiming** [cipchk/ngx-weui#73]
如题，我用angular-cli  引入npm ngx-weui，用DatePicker组建，我这边使用的service导入，我配置一些DatePicker默认选项，不生效

html 如下
        
        <div class="weui-cell">
            <div class="weui-cell__hd"><label for="" class="weui-label"><span>*</span>开始时间:</label></div>
            <div class="weui-cell__bd">
                <input class="weui-input" type="text" (click)="ChoseStartDate('date')" formControlName='StartDate' placeholder="请选择开始时间" readonly >
            </div>
        </div>

ts如下
    // 选择开始时间
    ChoseStartDate(type: string) {
        // this.pickerService.showDateTime('date',).subscribe((res: any) => {
        this.pickerService.showDateTime('date','2017-03-10',new Date(2017,1,9)).subscribe((res: any) => {
            this.activityForm.patchValue({
              StartDate:res.formatValue,
            })
        });
    }

页面没有报错，但是以上配置项都没有生效,请问具体如果配置默认日期，及限制日期

**Comment by cipchk** [comment]
检查一下所传递的信息，若还有问题，麻烦提供一个完整的 [plnkr](http://plnkr.co/edit/tpl:vrb1b6KrhvyqyCFXQ7zg) 可重现示例。
```ts
  /**
     * 构建一个日期时间选择器并显示
     *
     * @param {DatePickerType} [type] 类型，date-ym年月，date日期，datetime日期&时间（不包括秒），time时间（不包括秒）
     * @param {FORMAT_TYPE} [format] 日期格式化代码，实际是采用 DatePipe，所有代码内容和它一样
     * @param {Date} [value] 默认显示日期
     * @param {Date} [min] 最小时间范围
     * @param {Date} [max] 最大时间范围
     * @param {PickerOptions} [options] 配置项
     * @returns {Observable<any>} 务必订阅结果才会显示。
     */
    showDateTime(type?: DatePickerType, format?: FORMAT_TYPE,
        value?: Date, min?: Date, max?: Date, options?: PickerOptions)
```
