### ISSUE TITLE
DatePicker show no item when created dynamically

### ISSUE THREAD

**Issue by cuiliang** [cipchk/ngx-weui#76]
When the component was created dynamically, the popup will show with no item to select.

![image](https://user-images.githubusercontent.com/1972649/36656496-a8734186-1b03-11e8-832d-ce670c4f11a9.png)

this can be fixed by adding the following code:
```
ngOnInit(): void {
      this.genGroups();
    }
```

或者有其他更好的方法么？ 
要动态创建的字段类型是动态的，不一定是DatePicker，所以不适合去手动调用`componentRef.instance.ngOnChanges(null);` 这样的代码。

Thanks.

**Comment by cipchk** [comment]
能否提供一个 [stackblitz](https://stackblitz.com/edit/ngx-weui?file=app/app.component.ts) 重现示例呢?

**Comment by cuiliang** [comment]
我是通过ViewContainerRef.createComponent()的方式创建的，因为相关的组件比较多，没法放上来。 


代码中genGroups() 只有在onChanges 和 writeValue中调用。但是这种createComponent()后直接给instance属性设置值的方式不会触发onChanges，所以groups就没有生成。

还可以用另一个方模拟这个情况，就是在表单模版里不给任何属性设置值，也会不生成选择项。请看这个：
[https://stackblitz.com/edit/ngx-weui-nulpwx](https://stackblitz.com/edit/ngx-weui-nulpwx)

**Comment by cipchk** [comment]
的确如此，因为 `genGroups` 只在 `ngOnChanges` 触发时产生，这的确是一个不合理的行为。

示例中可以加上 `[min]="min"` 即可，我会在 `onInit` 中加入生成动作解决这一问题。

至于采用 `ViewContainerRef.createComponent()` 来构建，可以采用手动执行一次 `onChanges`，解决这一问题，我想若在 `onInit` 中加入这一动作，也会解决这一问题。因为核心在于无指定组件属性时无法触发 `onChanges` 引起的。

**Comment by cuiliang** [comment]
是的，我看到在那个service类手工调用了ngOnChanges(null)。 但是因为我这里需要根据参数动态创建任意的ControlValueAccessor的组件，所以手工调用ngOnChanges不是一个很好的方式。

另外 [setDisabledState(isDisabled: boolean): void {} ](https://github.com/cipchk/ngx-weui/blob/a69a32bef5ba55c1df48b538825b6faa77ace634/src/picker/picker-date.component.ts#L299 )这里，是不是需要更新一下this.disabled的值？

**Comment by cipchk** [comment]
关于无法组件参数问题，我想 `onInit` 应该可以解决这一问题，暂时你可以手工调用 `ngOnChanges` 解决。

> 关于响应式表单部分我需要重新对每个组件重新整理一下。

**Comment by cuiliang** [comment]
可以确认在ngOnInit里加this.genGroups()能够解决，我把代码直接放到项目里试过了。
辛苦啦！ 一个人维护这么大一个库很厉害。
