### ISSUE TITLE
为什么Picker中的DateTime在正常页面和Popup中在不同手机显示不同

### ISSUE THREAD

**Issue by QiZZ121** [cipchk/ngx-weui#77]
这是'iphone5'中popup中显示的日期
![image](https://user-images.githubusercontent.com/26375138/36881781-fc383f88-1e0a-11e8-8749-0953a160f672.png)
这是'iphone5'中没在popup中显示的日期->>
![image](https://user-images.githubusercontent.com/26375138/36881793-0fb967b2-1e0b-11e8-94fe-bc171d1db8c6.png)
该怎么解决这个年份看不到的问题

**Comment by QiZZ121** [comment]
可是明明是一样的使用确显示不同，这让我很苦恼

**Comment by cipchk** [comment]
你可以自行调整样式，虽然 这样子做不是很好。

**Comment by QiZZ121** [comment]
谢谢，是我自己修改样式的问题，打扰了
