### ISSUE TITLE
Plunker 有问题，无法使用picker组件

### ISSUE THREAD

**Issue by 81519434** [cipchk/ngx-weui#80]
![image](https://user-images.githubusercontent.com/9690089/37516514-567b0086-2949-11e8-97f5-21980328d7e4.png)
可能是延迟加载js，总是报404。

**Comment by 81519434** [comment]
http://plnkr.co/edit/bDD5zUVyHTuCZKhfcDl7?p=preview

**Comment by cipchk** [comment]
统一使用 https://stackblitz.com/edit/ngx-weui ，我会从文档上移除 Plnkr 相关的东西。
