### ISSUE TITLE
picker组件和dialog组件同时使用时，导致picker组件遮罩层无法显示

### ISSUE THREAD

**Issue by fengbean** [cipchk/ngx-weui#81]
![image](https://user-images.githubusercontent.com/31033272/37516630-b37989ba-2949-11e8-8a46-3ee053deebf8.png)

weui-dialog这个组件把样式.weui-mask, .weui-dialog {visibility: hidden;}激活了，导致picker这个组件样式被修改

**Comment by cipchk** [comment]
麻烦 https://stackblitz.com/edit/ngx-weui 重现一下，谢谢。
