### ISSUE TITLE
weui-date-picker选择时间和分钟时选不到晚上12点到一点这段时间

### ISSUE THREAD

**Issue by QiZZ121** [cipchk/ngx-weui#82]
weui-date-picker选择时间和分钟时选不到晚上12点到一点这段时间，选24直接跳到第二天1点了这是一个bug

**Comment by cipchk** [comment]
没有 `24` 点这一说，其实这是故意设计的，因为选 24 相当于第二天。

**Comment by QiZZ121** [comment]
但是就没有0点了啊 直接1点多了 这不符合实际吧，少一个小时啊

在 2018-03-17 11:20:18，"卡色" <notifications@github.com> 写道：


没有 24 点这一说，其实这是故意设计的，因为选 24 相当于第二天。

**Comment by cipchk** [comment]
哈，的确，我脑袋秀逗了。

**Comment by QiZZ121** [comment]
一个人维护这么多代码 难免会忽略这种小问题，一般晚上12点的确很模糊

在 2018-03-17 13:40:35，"卡色" <notifications@github.com> 写道：


哈，的确，我脑袋秀逗了。

**Comment by QiZZ121** [comment]
什么时候更新下版本呢

**Comment by QiZZ121** [comment]
@cipchk
