### ISSUE TITLE
Picker选择了日期，怎么清空已经选择的日期？ 比如手动选择了一个日期，，然后有个触发事件，就是清空之前所选的日期，，怎么解决

### ISSUE THREAD

**Issue by weber0000** [cipchk/ngx-weui#85]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

ngx-weui version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

Others:

</code></pre>

**Comment by cipchk** [comment]
`ngModle` 是一个双向绑定，你可以在外部给予一个 `null` 亦可。

**Comment by cipchk** [comment]
请告知 ngx-weui 版本号。

**Comment by weber0000** [comment]
1.2.2

**Comment by cipchk** [comment]
https://github.com/cipchk/ngx-weui/releases
