### ISSUE TITLE
现在文档组件不提供代码对照了吗

### ISSUE THREAD

**Issue by lichangfeng** [cipchk/ngx-weui#87]
作者您好！现在组件文档好像只提供api，没有代码对照了，以后都不提供了吗？

**Comment by cipchk** [comment]
不太明白你的意思，https://cipchk.github.io/ngx-weui/ 不是包含着DEMO&API吗？

**Comment by lichangfeng** [comment]
比如之前我在这个页面https://cipchk.github.io/ngx-weui/#/components/button，左边能看到组件效果，右边能看到demo代码，包括template css ts这三个的代码，是三个tab页下面展示的。

**Comment by cipchk** [comment]
https://github.com/cipchk/ngx-weui/blob/master/src/app/example/button/button.component.ts
我会在页面增加相应的按钮。

**Comment by lichangfeng** [comment]
您是说会跳转到demo代码所在的git地址吗？那好像现在跳转的不对，现在是直接跳转到组件源码了。

**Comment by huangjixin** [comment]
hi，楼主，你的组件写得很好，什么时候可以加上用法代码？
