### ISSUE TITLE
怎么使用accordion组件？

### ISSUE THREAD

**Issue by Zero09** [cipchk/ngx-weui#9]
如题，要怎么才能使用accordion组件呢？

**Comment by cipchk** [comment]
哈，accordion本身是我用来做example时用的，当下weui并没有对应的UI，不过我已经有这个打算要实现一个专门的 accordion 组件了。

如果你现在需要用的话，可以参考 `demo/src` 目录下的代码。

**Comment by Zero09** [comment]
ok，参考你的代码终于实现了。另外发现一个bug
home.component.html里面 *ngIf="si.show !== false" 
这边应该是 *ngIf="i.show !== false"

**Comment by cipchk** [comment]
release 1.0.7, see [CHANGELOG](https://github.com/cipchk/ngx-weui/blob/master/CHANGELOG.md).

If it solves the problem, please close this issue
