### ISSUE TITLE
把样例当中的Tabbar和Navbar代码样式拷贝上去未能和预期相符，请问作者在其它的地方有设置样式？

### ISSUE THREAD

**Issue by huangjixin** [cipchk/ngx-weui#90]

**Comment by cipchk** [comment]
https://github.com/cipchk/ngx-weui/blob/master/docs/how.md

**Comment by cipchk** [comment]
谢谢指正，这是文档的错误。

**Comment by Shakell** [comment]
@ayaka209 请问如果要使用less，直接新建一个文件styles.less就可以吗？还是需要用npm安装一下。谢谢

**Comment by ayaka209** [comment]
@Shakell 如果是angular-cli项目直接新建一个文件即可，因为它依赖less包，包含编译less的功能。
