### ISSUE TITLE
新版本的ngx-weui样式没有了？

### ISSUE THREAD

**Issue by fstanwh** [cipchk/ngx-weui#92]
以前的版本是可以正常调用，
调用方法
import { TabModule } from 'ngx-weui/tab';
import { InfiniteLoaderModule, InfiniteLoaderConfig } from 'ngx-weui/infiniteloader';
变成了
import { TabModule } from 'ngx-weui';
import { InfiniteLoaderModule, InfiniteLoaderConfig } from 'ngx-weui';
但样式没有了，是要其它途径引入样式文件吗

<link href="//res.wx.qq.com/open/libs/weui/1.1.2/weui.min.css" rel="stylesheet">
该样式文件已经引入
但
@import '~ngx-weui/index'; 这个样式还需要引入吗，尝试引入不成功。

## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

ngx-weui version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

Others:

</code></pre>

**Comment by fstanwh** [comment]
有样例说明吗？

**Comment by cipchk** [comment]
https://cipchk.github.io/ngx-weui/#/docs/style
