### ISSUE TITLE
ERROR in Metadata version mismatch for module E:/qunyao_server/qunyao_server/trunk/cjsr-web/node_modules/ngx-weui/weui.d.ts, found ver sion 4, expected 3

### ISSUE THREAD

**Issue by pangshangggg** [cipchk/ngx-weui#93]
ERROR in Metadata version mismatch for module E:/qunyao_server/qunyao_server/trunk/cjsr-web/node_modules/ngx-weui/weui.d.ts, found ver
sion 4, expected 3, resolving symbol SharedModule in E:/qunyao_server/qunyao_server/trunk/cjsr-web/src/app/shared/shared.module.ts, re
solving symbol SharedModule in E:/qunyao_server/qunyao_server/trunk/cjsr-web/src/app/shared/shared.module.ts

**Comment by cipchk** [comment]
Angular4 请使用 `1.1.x` 之前版本
