### ISSUE TITLE
超级严重的BUG：mask全局样式

### ISSUE THREAD

**Issue by cxy930123** [cipchk/ngx-weui#94]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[x] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

某些组件为`.mask-weui`设置了全局隐藏样式，导致picker组件常常不出现遮罩层，真是很烦恼啊

## Environment

<pre><code>
Angular version: X.Y.Z

ngx-weui version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

Others:

</code></pre>

**Comment by cipchk** [comment]
麻烦给一个具体的可[重现示例](https://stackblitz.com/edit/ngx-weui)，目前 examples 并无发现这类情况。

**Comment by cxy930123** [comment]
不，文档示例也有问题，虽然原理不一样，效果有点类似。
文档中的picker示例点击之后遮罩层是出现在input上，这是不对的。
![image](https://user-images.githubusercontent.com/7006257/39418352-893d3884-4c8c-11e8-8c1a-02bb36c3ed73.png)
不过如果通过服务的方式，又有全屏的遮罩层。
![image](https://user-images.githubusercontent.com/7006257/39418371-a245bc8e-4c8c-11e8-8927-23deb46bbc14.png)
![image](https://user-images.githubusercontent.com/7006257/39418378-adf72ffe-4c8c-11e8-9725-f4338c62d329.png)

**Comment by cipchk** [comment]
api 文档部分的示例，可能存在一些优先级的关系，而 [examples](https://cipchk.github.io/ngx-weui/#/example/picker) 本无存在此问题，我会修复API文档 部分，但应该和具体无关。

有关可能其他因素产生的问题，请麻烦在线重现一个，否则我需要在这个问题发费大量的时间才能了解原因，也请了解在下的时间成本。
