### ISSUE TITLE
dialog 的prompt不显示

### ISSUE THREAD

**Issue by jasminecjc** [cipchk/ngx-weui#95]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

![image](https://user-images.githubusercontent.com/13568376/39251039-e7a39b90-48d4-11e8-8d95-68608a4be4d3.png)

## Expected behavior
![image](https://user-images.githubusercontent.com/13568376/39251072-fab47e20-48d4-11e8-815e-fe758e461a3e.png)

## Environment
```
const cog = Object.assign({}, this.DEFCONFIG, <DialogConfig>{
      title: "请输入拒绝理由",
      skin: "auto",
      type: "prompt",
      confirm: "确认",
      cancel: "取消",
      input: "textarea"
    });
    this.srv.show(cog).subscribe((res: any) => {
      console.log(res);
    });
    return false;
```
Angular version: 5.0.0

ngx-weui version: 3.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

Others:

</code></pre>

**Comment by cipchk** [comment]
请尽可能通过 https://stackblitz.com/edit/ngx-weui 重现问题
