### ISSUE TITLE
使用demo中的popup和预期效果不一致，请问这个是需要配置styles.less文件吗？

### ISSUE THREAD

**Issue by Shakell** [cipchk/ngx-weui#97]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ x ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
![image](https://user-images.githubusercontent.com/33541501/39568026-266b28ec-4ec1-11e8-82de-2e7a040c006b.png)

## Expected behavior
![image](https://user-images.githubusercontent.com/33541501/39568050-4198095a-4ec1-11e8-9bb6-88a6dd467dbd.png)

## Environment

<pre><code>
Angular version: 5.2.9

ngx-weui version: 3.0.0

Others:

</code></pre>

**Comment by Shakell** [comment]
我在ts文件中添加`import { PopupComponent } from "ngx-weui/popup";`浏览器报错can't resolve import { PopupComponent } from "ngx-weui/popup

然后我试着添加这个`import { PopupComponent } from "../../node_modules/ngx-weui/popup/popup.component.d";`也是can't resolve，请问这个component应该如何正确添加呢？

**Comment by cipchk** [comment]
请尽可能通过 https://stackblitz.com/edit/ngx-weui 重现问题

**Comment by Shakell** [comment]
https://stackblitz.com/edit/ngx-weui-5tn3yc 
Can't find module:
ngx-weui/popup (@2.0.2)
