### ISSUE TITLE
ERROR in Error during template compile of 'SharedModule'   Function calls are not supported in decorators but 'InfiniteLoaderModule' was called.

### ISSUE THREAD

**Issue by pangshangggg** [cipchk/ngx-weui#98]
import {ButtonModule, InfiniteLoaderModule, SwiperModule} from "ngx-weui";
import { RecordListTempComponent } from './record-list-temp/record-list-temp.component';
/* Feature Modules */
import { ClipboardModule } from 'ngx-clipboard';
@NgModule({
  imports: [
    CommonModule,
    RouterModule,
    FormsModule,
    ReactiveFormsModule,
    ClipboardModule,
    InfiniteLoaderModule.forRoot(),
    ButtonModule.forRoot(),
    SwiperModule.forRoot(),
    // WeUiModule.forRoot()
  ],
  exports: [
    CommonModule,
    InfiniteLoaderModule,
    ButtonModule,
    SwiperModule,
    // WeUiModule,
    ClipboardModule,
    TempComponent,
    HeaderBarComponent,
    RecordListTempComponent,
  ],

**Comment by pangshangggg** [comment]
run ng build --prod show error,how to resolve

**Comment by cipchk** [comment]
Can you  with providing exact path for imports?

**Comment by zhangjie1314** [comment]
Me too

**Comment by zhangjie1314** [comment]
这是我的imports列表

`@NgModule({
    declarations: [AppComponent, NotFindComponent],
    imports: [
        BrowserModule,
        BrowserAnimationsModule,
        HttpClientModule,
        RoutingModule,
        JWeiXinModule.forRoot(),
        ToastModule.forRoot(),
        ToptipsModule.forRoot(),
        DialogModule.forRoot()
    ],
    providers: [
        {
            provide: HTTP_INTERCEPTORS,
            useClass: CustomHttpInterceptor,
            multi: true
        }
    ],
    bootstrap: [AppComponent]
})`

这是报错信息
`Date: 2018-05-07T13:47:07.544Z                                                     
Hash: 9fbdc79974794d0ee6ee
Time: 4678ms
chunk {scripts} scripts.f7f8ed7657d26ff5d204.bundle.js (scripts) 121 kB [initial] [rendered]
chunk {0} styles.f16377c7202d952f8a81.bundle.css (styles) 23.4 kB [initial] [rendered]
chunk {1} polyfills.997d8cc03812de50ae67.bundle.js (polyfills) 84 bytes [initial] [rendered]
chunk {2} main.ee32620ecd1edff94184.bundle.js (main) 84 bytes [initial] [rendered]
chunk {3} inline.318b50c57b4eba3d437b.bundle.js (inline) 796 bytes [entry] [rendered]

ERROR in Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'JWeiXinModule' was called.`

**Comment by zhangjie1314** [comment]
我把版本降到1.2.2就没有问题了

**Comment by cipchk** [comment]
我会在这两天发布支持 angular6 时同步修复这个问题。

**Comment by fengbean** [comment]
ERROR in Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'SwiperModule' was called.

不兼容angular6，打包加参数就报这个错，不加参数是可以打包成功的。
