### ISSUE TITLE
angular6无法使用ngx-weui

### ISSUE THREAD

**Issue by touchsky** [cipchk/ngx-weui#99]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
angular-cli新建的项目
angular6引入ngx-weui会报下面错误
ERROR in node_modules/ngx-weui/src/actionsheet/actionsheet.component.d.ts(3,10): error TS2305: Module '"D:/git项目/BMW-mobile/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/ngx-weui/src/actionsheet/actionsheet.service.d.ts(2,10): error TS2305: Module '"D:/git项目/BMW-mobile/node_modules/rxjs/Observable"' has no exported member 'Observable'.

style.less引用也会报
@import '~weui/src/style/weui';
@import '~ngx-weui/index';
'~ngx-weui/index' wasn't found. Tried - D:\git项目\BMW-mobile\src\~ngx-weui\index.less,npm://~ngx-weui\index,npm://~ngx-weui\index.less,~ngx-weui\index.less
      in D:\git项目\BMW-mobile\src\styles.less (line 3, column 0)
</code></pre>

## Environment

<pre><code>
Angular version: 6.0.0

ngx-weui version: 3.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

Others:

</code></pre>

**Comment by cipchk** [comment]
是的，需要再等一小会。

**Comment by lishewen** [comment]
我尝试想PR一个ng6的过来，结果发现里面的一个angular-split组件不兼容ng6，卡住了[捂脸]
